apiVersion: v1
kind: Service
metadata:
  name: shortner-app
  labels:
    app: shortner
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 5100
  selector:
    app: shortner
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shortner-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: shortner
        tier: frontend
    spec:
      containers:
      - name: shortner-app
        image: lusotycoon/shortner-backend
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 5100
