version: '3'
services:
  shortener:
    image: trukhinyuri/golinkshortener:latest
    ports:
      - 5100:5100
    networks:
     - redis-net
    depends_on:
      - redis
  redis:
    image: redis:4.0.11-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
 redis-net:

volumes:
  redis-data: